apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
      - name: todo-backend
        image: 100xdevs/todo-app-test:1
        ports:
        - containerPort: 3000
        volumeMounts: 
        - name: env-file
          readOnly: true           # the DbUrl will be stored here
          mountPath: "/app/secret" # <-----  this here becasue /app if we add only this then the source code will be erased fro m here 
      volumes:
      - name: env-file. #<--- this is the name of the file
        secret: 
          secretName: backend-secret # <--- this is pointing to the ops/sceret.yml ->> Service Name
          